Repository jenkinsci/simple-theme-plugin, pull requests merged in 2020-02, with the labels that each got.

#13 Import old changelog from wiki
  CHANGELOG.old.md
  LICENSE
  README.markdown
Labels: chore

#12 Fix for JENKINS-60275 - use getRootUrlFromRequest() for FavIcon script
  src/main/java/org/jenkinsci/plugins/simpletheme/FaviconUrlThemeElement.java
Labels: bug

#14 Add some badges to the README
  README.markdown
Labels: chore

#15 Require Jenkins 2.121.3
  pom.xml
  src/main/java/org/jenkinsci/plugins/simpletheme/FaviconUrlThemeElement.java
Labels: dependencies
