Repository jenkinsci/simple-theme-plugin, pull requests merged in 2025-01, with the labels that each got.

#229 Use `jenkins.baseline` to reduce bom update mistakes
  pom.xml
Labels: chore

#230 Use https: for scm URL, not ssh:
  pom.xml
Labels: chore

#231 Migrate from EE 8 to EE 9
  pom.xml
  src/main/java/org/codefirst/SimpleThemeDecorator.java
Labels: internal

#232 Migrate tests to JUnit5
  pom.xml
  src/test/java/org/jenkinsci/plugins/simpletheme/ConfigurationAsCodeTest.java
  src/test/java/org/jenkinsci/plugins/simpletheme/ConfigurationMigrationTest.java
  src/test/java/org/jenkinsci/plugins/simpletheme/SimpleThemeConfigurationTest.java
Labels: chore, java
